import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import "./theme-config.css";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import { Inter } from "next/font/google";
import AuthProvider from "./auth/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Theme
          appearance="light"
          accentColor="violet"
          className={inter.variable}
        >
          <AuthProvider>
            <NavBar />
            <main className="p-5">
              <Container size="3">{children}</Container>
            </main>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
