import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import ContentRoot from "./main";
import "./theme-config.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ContentRoot>{children}</ContentRoot>
      </body>
    </html>
  );
}
